### ISSUE TITLE
Problemas ao realizar uma compra

### ISSUE THREAD

**Issue by shooutz** [Bremado/BRPayments#6]
Estou testando o plugin em meu servidor de teste windows, quando tento fazer uma compra, o plugin me retorna um erro no console:
![image](https://github.com/Bremado/BRPayments/assets/120399502/2ff90359-8487-46e9-96bf-b68ebbdc56d2)

não sei se isso tem haver com o sistema que estou usando (windows) ou sla, já tive uns probreminha com decimal, e acho q isso tá sendo causado pelo **"."** no valor do produto
![image](https://github.com/Bremado/BRPayments/assets/120399502/14b5149a-717b-4335-bbbb-35ae431843a3)

infos:
paper-1.8
java 11.0.18
windows 10 22h2

**Comment by Bremado** [comment]
Problema corrigido, a versão 0.1.1-BETA já está disponível com o problema corrigido.
